services:
  botc-db:
    image: postgres:16
    container_name: botc-db
    restart: unless-stopped
    env_file: 
      - stack.env
    environment: 
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  botc-api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: botc-api
    restart: unless-stopped
    depends_on:
      - botc-db
    env_file:
      - stack.env
    environment:
      PGHOST: botc-db
      PGPORT: 5432
      
  botc-client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: botc-client
    restart: unless-stopped
    depends_on:
      - botc-api
    ports:
      - "3000:80"

volumes:
  pgdata:
